# file configuration
PRIVATE_KEYS_FILE_PATH = "data/private_keys.txt"
PROXIES_FILE_PATH = "data/proxies.txt"
DATABASE_FILE_PATH = "data/database.json"

# CLIENT CONFIGURATION
VERIFY_TX_TIMEOUT = 300
RETRY_DELAY_RANGE = [5, 10]
REQUEST_MAX_RETRIES = 10
WAIT_FOR_DEPOSIT_DELAY_RANGE = [60, 60]


# regex for matching the valid proxy format
PROXY_PATTERN = r"^([^:@\s]+):([^:@\s]+)@([a-zA-Z0-9.-]+|\d+\.\d+\.\d+\.\d+):(\d+)$"

# logs
LOGS_FILE_PATH = "data/logs/logs.log"

# OKX
ARB_NETWORK_FEE = 0.0001
ARB_OKX_CHAIN_NAME = "Arbitrum One"
OKX_WITHDRAW_TRIES = 5
OKX_WITHDRAW_DELAY_RANGE = [60, 60]
OKX_WAIT_FOR_WITHDRAWAL_FINAL_STATUS_DELAY_RANGE = [10, 10]
OKX_WAIT_FOR_WITHDRAWAL_FINAL_STATUS_ATTEMPTS = 100

# ORBITER
ORBITER_ARB_SCROLL_TRADING_FEE = 0.0012
ORBITER_MIN_SENT_VALUE = 0.001
ARBITRUM_ORBITER_CONTRACT_ADDRESS = "0x80C67432656d59144cEFf962E8fAF8926599bCF8"

# DEPLOYER
DEPLOYER_ABI_FILE_PATH = "data/custom_abi.json"
